### ISSUE TITLE
Dot in route returns 404 status code

### ISSUE THREAD

**Issue by hongaar** [jayhealey/Robots#3]
A request to /robots.txt returns the content generated by this package, but with a 404 status code. 

Related:

 - laravel/framework#3494
 - laravel/framework#6180

**Comment by jsisson** [comment]
Just finished working this through on my server, maybe it'll help for you.  My app was returning the proper output, but with a 404 status.

Nginx had a rule for handling robots.txt that was conflicting:

    location = /robots.txt  { access_log off; log_not_found off; }

...once I removed it everything was fine.

**Comment by jayhealey** [comment]
I don't believe this to be an issue with this plugin. Closing unless proven otherwise.

**Comment by AleemShaukat** [comment]
hi when i remove dot and percentage symbol from url parameter like (http://localhost:8000/activate/%242y%.sroG) to (http://localhost:8000/activate/242ysroG) then its work and Route accepted, if url contains these two characters then Route do not accepted that url and give 404 error in Laravel 5.3. Why its perform that behavior
