### ISSUE TITLE
Laravel 5 Compatibility?

### ISSUE THREAD

**Issue by nobodyiscertain** [jayhealey/Robots#5]
Hi there,

I installed this package and included the lines in my app config for the Service Provider and Facade but I'm getting the following error:

`BadMethodCallException in ServiceProvider.php line 226: Call to undefined method [package]`

Is this package L5 compatible?

**Comment by futhr** [comment]
+1

**Comment by farshid1** [comment]
I have the same problem. I see in one of the commits that L5 compatibility has been added.

**Comment by yukato** [comment]
+1
