### ISSUE TITLE
Class 'Robots' not found

### ISSUE THREAD

**Issue by 0x1ad2** [jayhealey/Robots#6]
Hi James,

I´m getting the following error: ![error](http://gyazo.com/95f12a03ad74096c7a26c639ada3a11c.png)

I tried to add an alias ('Robots' => 'Healey\Robots\Robots',) in the app.php file (I´m using L4) but that didn't work either: ![alias](http://gyazo.com/00fa26ad6ea070098382909c4ea2604c.png)

What to do?

**Comment by Rover350z** [comment]
composer update/install/dump-autoload?

**Comment by 0x1ad2** [comment]
@Rover350z that's the first thing I tried (dump the autoload files) but that didn't work also the class is called Robots so it's strange it could not find it. 

![image](http://gyazo.com/e27c1a8676a40cd5a209261f8b0901e9.png)

**Comment by Rover350z** [comment]
In your previous screenshot i saw you prefixing the classes with "\".

What if you remove the backslash and add the alias, does that work?

**Comment by 0x1ad2** [comment]
@Rover350z I've tried that and I'll get the same error as In my second screenshot, It seems to find the class but can't call the method statically.

![Image](http://gyazo.com/2cda2c598ddc0e24002e95460d22fefe.png)

**Comment by 0x1ad2** [comment]
I've tried to reproduce the error in another environment and seems to be working there, please close the issue (if you want).

**Comment by 0x1ad2** [comment]
I've tried to reproduce the issue in another project and it seems to be working there, so I think there's something in my other project that's broken.
